### ISSUE TITLE
Translate to PHP

### ISSUE THREAD

**Issue by linuxscout** [linuxscout/yaraspell#1]
Translate the code to PHP/MySQL
- use ar-php library [ar-php](http://ar-php.orgl)
- use php code from [Norvig](http://norvig.com/spell-correct.html)

**Comment by ATouhou** [comment]
Looking forward

**Comment by muotaz** [comment]
Dear Taha;

First I would like to thank you for your efforts in open source Arabic NLP, and indeed porting this to PHP would be great.
Having tried the Python code, I believe that the PHP version would be better off with a ported version of Tashaphyne, rather than the Stemmer included in ar-php (with great gratitdue to Mr Asham3a).
Is it ok to email you with some question regarding the yara3 code? Or is it better to discuss it here in a pull request ?

Kind regards;

**Comment by linuxscout** [comment]
Salam,
I started porting it to php, you can see it in [yaraspell-php](https://github.com/linuxscout/yaraspell/tree/master/yaraspell-php)
I use Mysql as a database for dictionary, 
The main issue is to use more compact dictionary to make speller fast, or use a data structure which insure small size to be imported and a researchable.
the other issue is to have a standard stemmer, which give the same dictionary and segmentation for many language, I think about [Assem's stemmer](https://github.com/assem-ch/arabicstemmer)
@assem-ch.

**Comment by muotaz** [comment]
Salam;

I have tested the stemmer at http://snowballstem.org/demo.html with the following phrase:
ذهب الولد إلى المدرسة وقال هناك أن الجو جميل جداً في الباحة الجميلة الرائعة 
The result was
ذهب ولد الي مدرس قال هنا ان الجو جميل جدا في باح جميل رايع 

It removed the _ta' marboutah_ from _madrasah_ and _baha_.
So the question is, is the stemmer supposed to _stem_ the word in the sense of extracting the linguistic root, or just remove any possible affixes from the word to make it possible to look it up in the dictionary ?
Good to hear that the PHP version is already there,  I will download it and have a look at it.

_salam_

**Comment by linuxscout** [comment]
@assem-ch

**Comment by linuxscout** [comment]
@assem-ch

**Comment by assem-ch** [comment]
@muotaz The project intend to offer 3 levels of the stemming:
- word without affixes , done
- infinitive or morpheme , not yet
- root, not yet

**Comment by muotaz** [comment]
@assem-ch 
Thanks brother for clearing that out, well that means it is not quite usable in projects then. 
So, we'd have to port the Python Tashaphyne stemmer to php if we want to use one in the project.

**Comment by assem-ch** [comment]
@muotaz if you are looking for root or (infinitive/morpheme).
